/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthlayoutImport } from './routes/_auth_layout'
import { Route as ApplayoutImport } from './routes/_app_layout'
import { Route as IndexImport } from './routes/index'
import { Route as AuthlayoutAuthSignupImport } from './routes/_auth_layout/auth/signup'
import { Route as AuthlayoutAuthLoginImport } from './routes/_auth_layout/auth/login'
import { Route as ApplayoutAppMycollectionsImport } from './routes/_app_layout/app/my_collections'
import { Route as ApplayoutAppMoviesImport } from './routes/_app_layout/app/movies'
import { Route as ApplayoutAppCollectionIndexImport } from './routes/_app_layout/app/collection/index'
import { Route as ApplayoutAppMovieIdImport } from './routes/_app_layout/app/movie/$id'
import { Route as ApplayoutAppCollectionIdImport } from './routes/_app_layout/app/collection/$id'

// Create/Update Routes

const AuthlayoutRoute = AuthlayoutImport.update({
  id: '/_auth_layout',
  getParentRoute: () => rootRoute,
} as any)

const ApplayoutRoute = ApplayoutImport.update({
  id: '/_app_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthlayoutAuthSignupRoute = AuthlayoutAuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => AuthlayoutRoute,
} as any)

const AuthlayoutAuthLoginRoute = AuthlayoutAuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => AuthlayoutRoute,
} as any)

const ApplayoutAppMycollectionsRoute = ApplayoutAppMycollectionsImport.update({
  path: '/app/my_collections',
  getParentRoute: () => ApplayoutRoute,
} as any)

const ApplayoutAppMoviesRoute = ApplayoutAppMoviesImport.update({
  path: '/app/movies',
  getParentRoute: () => ApplayoutRoute,
} as any)

const ApplayoutAppCollectionIndexRoute =
  ApplayoutAppCollectionIndexImport.update({
    path: '/app/collection/',
    getParentRoute: () => ApplayoutRoute,
  } as any)

const ApplayoutAppMovieIdRoute = ApplayoutAppMovieIdImport.update({
  path: '/app/movie/$id',
  getParentRoute: () => ApplayoutRoute,
} as any)

const ApplayoutAppCollectionIdRoute = ApplayoutAppCollectionIdImport.update({
  path: '/app/collection/$id',
  getParentRoute: () => ApplayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app_layout': {
      id: '/_app_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ApplayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth_layout': {
      id: '/_auth_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_app_layout/app/movies': {
      id: '/_app_layout/app/movies'
      path: '/app/movies'
      fullPath: '/app/movies'
      preLoaderRoute: typeof ApplayoutAppMoviesImport
      parentRoute: typeof ApplayoutImport
    }
    '/_app_layout/app/my_collections': {
      id: '/_app_layout/app/my_collections'
      path: '/app/my_collections'
      fullPath: '/app/my_collections'
      preLoaderRoute: typeof ApplayoutAppMycollectionsImport
      parentRoute: typeof ApplayoutImport
    }
    '/_auth_layout/auth/login': {
      id: '/_auth_layout/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthlayoutAuthLoginImport
      parentRoute: typeof AuthlayoutImport
    }
    '/_auth_layout/auth/signup': {
      id: '/_auth_layout/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthlayoutAuthSignupImport
      parentRoute: typeof AuthlayoutImport
    }
    '/_app_layout/app/collection/$id': {
      id: '/_app_layout/app/collection/$id'
      path: '/app/collection/$id'
      fullPath: '/app/collection/$id'
      preLoaderRoute: typeof ApplayoutAppCollectionIdImport
      parentRoute: typeof ApplayoutImport
    }
    '/_app_layout/app/movie/$id': {
      id: '/_app_layout/app/movie/$id'
      path: '/app/movie/$id'
      fullPath: '/app/movie/$id'
      preLoaderRoute: typeof ApplayoutAppMovieIdImport
      parentRoute: typeof ApplayoutImport
    }
    '/_app_layout/app/collection/': {
      id: '/_app_layout/app/collection/'
      path: '/app/collection'
      fullPath: '/app/collection'
      preLoaderRoute: typeof ApplayoutAppCollectionIndexImport
      parentRoute: typeof ApplayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ApplayoutRoute: ApplayoutRoute.addChildren({
    ApplayoutAppMoviesRoute,
    ApplayoutAppMycollectionsRoute,
    ApplayoutAppCollectionIdRoute,
    ApplayoutAppMovieIdRoute,
    ApplayoutAppCollectionIndexRoute,
  }),
  AuthlayoutRoute: AuthlayoutRoute.addChildren({
    AuthlayoutAuthLoginRoute,
    AuthlayoutAuthSignupRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app_layout",
        "/_auth_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app_layout": {
      "filePath": "_app_layout.tsx",
      "children": [
        "/_app_layout/app/movies",
        "/_app_layout/app/my_collections",
        "/_app_layout/app/collection/$id",
        "/_app_layout/app/movie/$id",
        "/_app_layout/app/collection/"
      ]
    },
    "/_auth_layout": {
      "filePath": "_auth_layout.tsx",
      "children": [
        "/_auth_layout/auth/login",
        "/_auth_layout/auth/signup"
      ]
    },
    "/_app_layout/app/movies": {
      "filePath": "_app_layout/app/movies.tsx",
      "parent": "/_app_layout"
    },
    "/_app_layout/app/my_collections": {
      "filePath": "_app_layout/app/my_collections.tsx",
      "parent": "/_app_layout"
    },
    "/_auth_layout/auth/login": {
      "filePath": "_auth_layout/auth/login.tsx",
      "parent": "/_auth_layout"
    },
    "/_auth_layout/auth/signup": {
      "filePath": "_auth_layout/auth/signup.tsx",
      "parent": "/_auth_layout"
    },
    "/_app_layout/app/collection/$id": {
      "filePath": "_app_layout/app/collection/$id.tsx",
      "parent": "/_app_layout"
    },
    "/_app_layout/app/movie/$id": {
      "filePath": "_app_layout/app/movie/$id.tsx",
      "parent": "/_app_layout"
    },
    "/_app_layout/app/collection/": {
      "filePath": "_app_layout/app/collection/index.tsx",
      "parent": "/_app_layout"
    }
  }
}
ROUTE_MANIFEST_END */
